### ISSUE TITLE
Use `S3Bucket` from `prefect-aws` instead of `RemoteFileSystem` to access MinIO

### ISSUE THREAD

**Issue by rpeden** [rpeden/prefect-docker-compose#5]
`RemoteFileSystem` is flexible, but its reliance on `aiobotocore` means it is pinned to an older version of `botocore`, which sometimes causes API errors when accessing S3 and S3-compatible storage. 

Since the `S3 Bucket` from the `prefect-aws` collection has excellent MinIO support, this repo should use `S3Bucket` to access MinIO to ensure optimal developer experience.

**Comment by tomasrollo** [comment]
In the Prefect UI, how do you specify the MinIO URL when adding the `S3 bucket` block? Or is it possible when creating the block some other way (CLI, via API)? Thx!

**Comment by lwllendbro** [comment]
> In the Prefect UI, how do you specify the MinIO URL when adding the `S3 bucket` block? Or is it possible when creating the block some other way (CLI, via API)? Thx!

When you add the s3 block add a json in the settings section:
{
  "key": "Key",
  "secret": "Secret",
  "client_kwargs": {
    "endpoint_url": "http://minio:9000" 
  }
}

**Comment by tomasrollo** [comment]
That's what I thought but there does not seem to be a settings section in the S3 block in the GUI?

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/6460459/236406218-fd50b8e3-9889-4f27-b85c-a27e5bdfda29.png">

**Comment by rpeden** [comment]
@tomasrollo There are two different S3 blocks - one is just called `S3` and the other is called `S3 Bucket`:

<img width="550" alt="Screenshot 2023-05-05 at 7 40 55 PM" src="https://user-images.githubusercontent.com/228762/236585421-a8c52674-7a4c-4512-b235-8784d7fd7d7d.png">

`S3 Bucket` has a section for MinIO credentials. The catch is that you need to install the `prefect-aws` pip package if you want to use `S3 Bucket` in your own Prefect server. 

The easiest way to do this is via the EXTRA_PIP_PACKAGES environment variable. I just updated `docker-compose.yml` to add a commented-out env variable that will install `prefect-aws`. If you uncomment that and run the server container, you should see the `S3 Bucket` block.

Note that I also updated the server container entrypoint; `EXTRA_PIP_PACKAGES` gets processed in the Prefect container's `/opt/prefect/entrypoint.sh` script, which wasn't being called before. 

So if you want to retrofit `EXTRA_PIP_PACKAGES` into your existing `docker-compose.yml`, you will need to update the entrypoint as well. 

I hope that helps, but feel free to post again if you run into any problems!

**Comment by rpeden** [comment]
@tomasrollo I should add that the reason you'd want to use `S3 Bucket` is that it accepts a MinIOCredentials block that lets you set the server URL. 

I hadn't realized the Settings section was removed from the old `S3` block. My apologies; I need to update the README. 

I think I'll need to just install `prefect-aws` by default and update the Minio instructions accordingly to show the new block. I'll try to do the README update this weekend.

**Comment by MrChadMWood** [comment]
@rpeden After making this change and utilizing S3-Bucket block document type, how should it be referenced from the CLI when attempting to copy the flows into the bucket?

Referring to your [original guide](https://github.com/rpeden/prefect-docker-compose):
`prefect deployment build -sb "remote-file-system/your-storage-block-name" -n "Awesome MinIO deployment" -q "awesome" "flow.py:greetings"`

I've attempted modifying this to:
`prefect deployment build -sb "s3bucket/minio" -n "Awesome MinIO deployment" -q "awesome" "flow.py:greetings"`

I get this error when using `s3bucket`:
`ValueError: Unable to find block document named minio for block type s3bucket`

and similarly, I also tried `s3-bucket`. I receive the following error when using `s3-bucket`:
`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

It may be worth mentioning, I created the minio_credentials block using the access_key (formerly "service account") info, not the actual root user login. The nomenclature used on the fields in the Prefect UI seem to indicate maybe I should have used an actual user/pass for the root user. Is that right?

**Comment by MrChadMWood** [comment]
FYI, I was able to confirm that the minio credential block is configured correctly, because I got this to work:

```
from prefect_aws import MinIOCredentials
minio_credentials = MinIOCredentials.load("minio-cred")
s3_client = minio_credentials.get_boto3_session().client(
    service_name="s3",
    endpoint_url="http://localhost:9000"
)
print(s3_client)

<botocore.client.S3 object at 0x7fba6df9b110>
```

So, I guess that rules out improper credentials?

**Comment by MrChadMWood** [comment]
@rpeden 

I have an issue where I am able to get `prefect-gitlab` accessible to the Prefect Server and UI, by using the `EXTRA_PIP_PACKAGES` option in the docker compose file. This allows to make the gitlab block from the UI.

I attempt to run a flow stored in GitLab, but the Prefect Agent fails because it does not also have access to the `prefect-gitlab` dependency. I've also checked, and `EXTRA_PIP_PACKAGES` does not work when specified in the Agent profile of the Docker Compose file [ref](https://github.com/PrefectHQ/prefect/issues/5195).

What would be the correct way to proceed? I can't seem to find a way to get the agent access to the package it needs.

**Comment by rpeden** [comment]
@MrChadMWood the agent uses the same Docker image as everything else, so EXTRA_PIP_PACKAGES should work there, too. I'll give it a quick try and post an update if it works for me.

**Comment by MrChadMWood** [comment]
@rpeden Thanks. I found a thread in the community forum where it looks like someone experienced the same issue. Please have a look there if you can.

**Comment by rpeden** [comment]
@MrChadMWood it was caused by the way I was overriding the entrypoint for the agent. I'll update it in the repo but this should make EXTRA_PIP_PACKAGES work:

```
## Prefect Agent
  agent:
    image: prefecthq/prefect:2.10.13-python3.11
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
      - EXTRA_PIP_PACKAGES=prefect-gitlab
    profiles: ["agent"]
```

Adding `"/opt/prefect/entrypoint.sh"` to the `entrypoint` array makes it work since that's the script the pulls the extra packages.

**Comment by MrChadMWood** [comment]
@rpeden 

I made that adjustment, unfortunately it had no effect in my case.

```
  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.10.16-python3.11
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "default"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - EXTRA_PIP_PACKAGES:prefect-gitlab prefect-aws
    profiles: ["agent"]
```
Error:
```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 331, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments.py", line 192, in load_flow_from_flow_run
    storage_block = Block._from_block_document(storage_document)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/blocks/core.py", line 618, in _from_block_document
    else cls.get_block_class_from_schema(block_document.block_schema)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/blocks/core.py", line 672, in get_block_class_from_schema
    return cls.get_block_class_from_key(block_schema_to_key(schema))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/blocks/core.py", line 683, in get_block_class_from_key
    return lookup_type(cls, key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/dispatch.py", line 185, in lookup_type
    raise KeyError(
KeyError: "No class found for dispatch key 'gitlab-repository' in registry for type 'Block'."
```

In the meantime, I was looking into MinIO as a temporary solution instead of GitLab.
When I use the `s3-bucket` block type, I'm still required to run `pip install prefect-aws && prefect register block -m prefect_aws` from the CLI in order to make a deployment. This is despite `prefect-aws` named inside the `EXTRA_PIP_PACKAGES` field. If I do not run the install&&register, I get the same error:
`KeyError: "No class found for dispatch key 's3-bucket' in registry for type 'Block'."`

However, once I run the install&&register code to get it working, it fails elsewhere:
`botcore.exceptions.NoCredentialsError: Unable to locate credentials`

I can't seem to get any code storage working beside local storage.

**Comment by MrChadMWood** [comment]
I'll share my entire setup, hopefully it helps.

OS: CentOS7 in VMBox
Docker Compose:
```
version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]
  
  ### MinIO for flow storage
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.10.16-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://HOSTNAME:4200/api
      - PREFECT_API_URL=http://HOSTNAME:4200/api

      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      - EXTRA_PIP_PACKAGES:prefect-gitlab prefect-aws
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.10.16-python3.11
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "default"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - EXTRA_PIP_PACKAGES:prefect-gitlab prefect-aws
    profiles: ["agent"]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.10.16-python3.11
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["cli"]
      
volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network
```
