### ISSUE TITLE
More than 2 queue in one agent.

### ISSUE THREAD

**Issue by NonlinearNimesh** [rpeden/prefect-docker-compose#6]
Hi i was using the provided docker compose in this repository, and it works file. I got an issue when i tried to run the 3rd queue in the agent. I wanted to ask that it this a limitation that one agent container can run only 2 queue or is there something i am doing wrong here.
Below is my agent container:
```
  agent:
    image: prefecthq/prefect:2.7.7-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "first_queue", "second_queue", "third_queue"]
    volumes:
      - "./flows:/root/flows"
      - "./flows/tmp:/tmp"
    environment:
      - PREFECT_API_URL=http://IP:4200/api
```
When i add queue "third_queue" then it throws an error, but works fine with "first_queue" and "second_queue"

Can anyone please help me on this.

Thanks.
